import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderServer from "@/blocks/global/Header/server";
import FooterServer from "@/blocks/global/Footer/server";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning className="snap-y snap-proximity">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
      >
        <HeaderServer />
        {children}
        <FooterServer />
      </body>
    </html>
  );
}
