import type { Metadata } from "next";
import "./globals.css";
import HeaderServer from "@/blocks/global/Header/server";
import FooterServer from "@/blocks/global/Footer/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className="snap-y snap-proximity"
    >
      <body className={`antialiased font-outfit`}>
        <HeaderServer />
        {children}
        <FooterServer />
      </body>
    </html>
  );
}
